/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.csvwilberth;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author wmgc5
 */
public class Vista extends javax.swing.JFrame {
    ManejoFichero fichero = new ManejoFichero();
    

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Importar = new javax.swing.JToggleButton();
        Guardar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Exportar = new javax.swing.JToggleButton();
        Nuevo = new javax.swing.JToggleButton();
        matriculajTextField1 = new javax.swing.JTextField();
        apellidoPjTextField1 = new javax.swing.JTextField();
        apellidoMjTextField1 = new javax.swing.JTextField();
        nombresjTextField1 = new javax.swing.JTextField();
        AtrasjToggleButton1 = new javax.swing.JToggleButton();
        AdelantejToggleButton2 = new javax.swing.JToggleButton();
        MateriajTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CalificacionjTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Importar.setText("Importar");
        Importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Matricula");

        jLabel2.setText("Apellido P");

        jLabel3.setText("Apellido M");

        jLabel4.setText("Nombres");

        Exportar.setText("Exportar");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        matriculajTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculajTextField1ActionPerformed(evt);
            }
        });

        apellidoPjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoPjTextField1ActionPerformed(evt);
            }
        });

        apellidoMjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoMjTextField1ActionPerformed(evt);
            }
        });

        nombresjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresjTextField1ActionPerformed(evt);
            }
        });

        AtrasjToggleButton1.setText("ATRAS");
        AtrasjToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasjToggleButton1ActionPerformed(evt);
            }
        });

        AdelantejToggleButton2.setText("ADELANTE");
        AdelantejToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdelantejToggleButton2ActionPerformed(evt);
            }
        });

        MateriajTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriajTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Materia");

        jLabel6.setText("Calificacion");

        CalificacionjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalificacionjTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MateriajTextField1)
                            .addComponent(apellidoMjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(apellidoPjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(matriculajTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(nombresjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(CalificacionjTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AtrasjToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Importar)
                        .addGap(40, 40, 40)
                        .addComponent(Nuevo)
                        .addGap(39, 39, 39)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exportar)
                    .addComponent(AdelantejToggleButton2))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(matriculajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apellidoPjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidoMjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombresjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MateriajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CalificacionjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Importar)
                    .addComponent(Nuevo)
                    .addComponent(Guardar)
                    .addComponent(Exportar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(AtrasjToggleButton1)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdelantejToggleButton2)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void apellidoPjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoPjTextField1ActionPerformed
        // TODO add your handling code here:
        apellidoPjTextField1.setEnabled(false);
    }//GEN-LAST:event_apellidoPjTextField1ActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
        /*
        ListaAlumnos nuevoAlumno = new ListaAlumnos();
        nuevoAlumno.setMatricula(matriculajTextField1.getText());
        nuevoAlumno.setPrimerApellido(apellidoPjTextField1.getText());
        nuevoAlumno.setSegundoApellido(apellidoMjTextField1.getText());
        nuevoAlumno.setNombres(nombresjTextField1.getText());
        listaAlumnos.add(nuevoAlumno);
        
        */
        fichero.guardarAlumno(matriculajTextField1, MateriajTextField1, CalificacionjTextField2);
        
       
        fichero.borrarAlumnos(fichero.getNavegador());
        if(fichero.confirmarCaptura()){
            MateriajTextField1.setEnabled(false);
            CalificacionjTextField2.setEnabled(false);
            matriculajTextField1.setText("");
       
            apellidoPjTextField1.setText("");
           
            apellidoMjTextField1.setText("");
            
            nombresjTextField1.setText("");
            MateriajTextField1.setText("");
            
            CalificacionjTextField2.setText("");
            Nuevo.setEnabled(false);

        }
       
       
        
    }//GEN-LAST:event_NuevoActionPerformed

    private void ImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarActionPerformed
        // TODO add your handling code here:
        
        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos csv", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        /*
        int seleccionar = seleccionarArchivo.showOpenDialog(this);
        if(seleccionar == JFileChooser.APPROVE_OPTION){
            File archivo =seleccionarArchivo.getSelectedFile();
            guardarArchivo(archivo);
        }
        */

        if(seleccionarArchivo.showDialog(this, "ABRIR CSV")==JFileChooser.APPROVE_OPTION){
            File archivo =seleccionarArchivo.getSelectedFile();
            if(archivo.getName().endsWith("csv")){
                fichero.importarArchivos(archivo);
                if(fichero.getCantidadColumnas()==4){
                    
                    MateriajTextField1.setEnabled(true);
                   CalificacionjTextField2.setEnabled(true);
  
                    fichero.inicio(matriculajTextField1, apellidoPjTextField1, apellidoMjTextField1, nombresjTextField1);
                    fichero.setImportarConfirmado();
                       
                    JOptionPane.showMessageDialog(null, "Archivo seleccionado de forma correcta");
                }else{
                    JOptionPane.showMessageDialog(null, "Cantidad de columnas incorrectas");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "El archivo seleccionado no tiene la extension csv");
            }
            
           
            /*
            if(archivo.endsWith("csv")){

            }
            */

        }



    }//GEN-LAST:event_ImportarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos csv", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        /*
        int seleccionar = seleccionarArchivo.showOpenDialog(this);
        if(seleccionar == JFileChooser.APPROVE_OPTION){
            File archivo =seleccionarArchivo.getSelectedFile();
            guardarArchivo(archivo);
        }
        */
        if(fichero.getImportarConfirmado()==1){

            if(fichero.confirmarCaptura()){
                if(seleccionarArchivo.showDialog(this, "GUARDAR CSV")==JFileChooser.APPROVE_OPTION){
                    File archivo =seleccionarArchivo.getSelectedFile();
                    if(archivo.getName().endsWith("csv")){
                        fichero.exportarArchivo(archivo);
                        
                        
                       
                        
        
                    }else{
                        JOptionPane.showMessageDialog(null, "Se debe agregar la extension .csv");
                    }
                    
                   
                    /*
                    if(archivo.endsWith("csv")){
        
                    }
                    
        */
                }
                        
            }else{
                JOptionPane.showMessageDialog(null, "No se han registrado todas las calificaciones");
            }
            
            
            

        }
        else{
            JOptionPane.showMessageDialog(null, "DEBES IMPORTAR EL ARCHIVO CSV");

        }
        
        

    }//GEN-LAST:event_GuardarActionPerformed

    private void matriculajTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculajTextField1ActionPerformed
        // TODO add your handling code here:
        matriculajTextField1.setEnabled(false);
    }//GEN-LAST:event_matriculajTextField1ActionPerformed

    private void apellidoMjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMjTextField1ActionPerformed
        // TODO add your handling code here:
        apellidoMjTextField1.setEnabled(false);
    }//GEN-LAST:event_apellidoMjTextField1ActionPerformed

    private void nombresjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresjTextField1ActionPerformed
        // TODO add your handling code here:
        nombresjTextField1.setEnabled(false);
    }//GEN-LAST:event_nombresjTextField1ActionPerformed

    private void AtrasjToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasjToggleButton1ActionPerformed
        // TODO add your handling code here:
        fichero.atras();
        fichero.inicio(matriculajTextField1, apellidoPjTextField1, apellidoMjTextField1, nombresjTextField1);
    }//GEN-LAST:event_AtrasjToggleButton1ActionPerformed

    private void MateriajTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriajTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MateriajTextField1ActionPerformed

    private void CalificacionjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalificacionjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalificacionjTextField2ActionPerformed

    private void AdelantejToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdelantejToggleButton2ActionPerformed
        // TODO add your handling code here:
        fichero.delante();
        fichero.inicio(matriculajTextField1, apellidoPjTextField1, apellidoMjTextField1, nombresjTextField1);
    }//GEN-LAST:event_AdelantejToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AdelantejToggleButton2;
    private javax.swing.JToggleButton AtrasjToggleButton1;
    javax.swing.JTextField CalificacionjTextField2;
    private javax.swing.JToggleButton Exportar;
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JToggleButton Importar;
    javax.swing.JTextField MateriajTextField1;
    private javax.swing.JToggleButton Nuevo;
    javax.swing.JTextField apellidoMjTextField1;
    javax.swing.JTextField apellidoPjTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    javax.swing.JTextField matriculajTextField1;
    javax.swing.JTextField nombresjTextField1;
    // End of variables declaration//GEN-END:variables
}
